name: Build & Publish to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ghpages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install --no-audit --no-fund

      - name: Build
        run: npm run build

      # 🔍 DEBUG: verifica se o index aponta para /<repo>/assets/...
      - name: Inspect dist
        run: |
          echo "---- dist tree ----"
          ls -la dist | head -n 50
          echo "---- first script src in dist/index.html ----"
          grep -o 'src="/[^"]*assets/[^"]*\.js"' dist/index.html || true

      # SPA fallback (evita branco em rotas hash/direct)
      - name: Ensure 404 for SPA
        run: cp -f dist/index.html dist/404.html

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
